#+title: TODO

* TODO Add cryptography
The cryptography chosen was RSA (private and public key). To make it work I decided to use OpenSSL lib. Right now I can encrypt, decrypt and go from EVP_PKEY type to QString.

- [X] Check exchange data procedure (It shouldn't contain cryptography)
  1) Self connect to peer (not saved)
     1. Server::startNewConn()
     2. exchangeData()
     3. connect: TcpSocket::connected () -> ?????
     4. connect: TcpSocket::readyRead () -> ?????
  2) Self connect to peer (saved)
     1. exchangeData()
        ...
  3) Peer connect to self (both)
     1. Serve::handleNewConnection()
     2. connect: QTcpSocket::readyRead () -> ?????
- [X] Check exchange of messages (It should contain cryptography)
- [-] Test it to see if it works.
  - [X] It works on linux?
  - [ ] It works on windows?

* DONE Load and save chat
right now I'm proposing peers to have the chat as an attribute and session manager will actually update it or not, save it or not, load it or not, etc...

** <<UPDATE 2026-03-12>> Messages are now handled by peers themselves
+The loading and saving needs polishing (it doesn't work, but it doesn't crash either).+
It just wasn't saving it actually.

I noticed two bugs:

*** <<BUG>> peer is already connected and online
this bug appeared when I opened the app and there was already a saved peer but it wasn't actually online and connected

*** <<BUG>> signal not found
the following error appeared out of nowhere:
#+begin_src bash
qt.core.qobject.connect: QObject::connect(QTcpSocket, QTcpSocket): signal not found
#+end_src
find out what's going on.

* DONE Automatic reconnections
* DONE <<DEBUG>>
1. A starts
2. B starts
3. B connects to A
   1. A accepts
4. B closes
5. B reopens
   1. B tries to connect to every saved peer (A)
   2. Something happens ???
   3. B tries to send message to A
   4. B crashes (segmentation fault) at
      #+begin_src c++
        void Peer::sendMsg(Message msg) {
          qint64 bytes = m_conn->write(msg.toBytes()); // <<<< segfaults
        }
      #+end_src

