; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5EFC6795-1A89-45B9-8B69-2C732C763B72}
AppName=OpenP2P
AppVersion=0.1
;AppVerName=OpenP2P 0.1
AppPublisher=i3elj
AppPublisherURL=https://www.github.com/i3elj/OpenP2P
AppSupportURL=https://www.github.com/i3elj/OpenP2P
AppUpdatesURL=https://www.github.com/i3elj/OpenP2P
DefaultDirName={autopf}\OpenP2P
UninstallDisplayIcon={app}\openp2p_app.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=OpenP2P-Setup
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\windows\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\OpenP2P"; Filename: "{app}\openp2p_app.exe"
Name: "{autodesktop}\OpenP2P"; Filename: "{app}\openp2p_app.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\openp2p_app.exe"; Description: "{cm:LaunchProgram,OpenP2P}"; Flags: nowait postinstall skipifsilent

